#!/bin/bash

currentBranch=$(git branch --show-current)

# Rebase your current base with main
git checkout $1 || exit 1
git pull --rebase
git checkout ${currentBranch}

# This checks to see if your branch is already up to date with main. This should not cause it to fail, so
# check the response and continue only if it says up to date, else fail because an error happened.
responseMessage=$(git rebase $1 2>&1)
if [[ $responseMessage=="Current branch ${currentBranch} is up to date." ]]; then
	echo "No changes to merge with for main, continuing."
else
	if [[ $?!=0 ]]; then
		echo "Error with rebase, quitting."
		exit 1
	fi
fi
